# Generated by Django 5.1.7 on 2025-03-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='category',
            new_name='categoryid',
        ),
    ]
